### ISSUE TITLE
Exception 500 for multi-layer federated content search

### ISSUE THREAD

**Issue by Akron** [KorAP/KorapSRU#3]
Currently even simple queries using multi-layer FCS result in 500 exceptions. To reproduce,

1. go to https://contentsearch.clarin.eu/
2. switch to "Multi-Layer Federated Content Search (FCS-QL)"
3. add search term (e.g. "Kaffee")
4. limit the search to corpora provided by the KorAP FCS endpoint
5. search

Expected result: Some KWICs.
Actual result: 500 error messages.

The problem was reported by [Teoric](https://github.com/teoric).

**Comment by margaretha** [comment]
Thanks for the report. The problem has been fixed in 8e0c3d0ebfc7520bc9743e11da7c3fb7b8adcf06.
